name: Test Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Print runner info
        run: |
          echo "Runner está funcionando!"
          uname -a
